                                                                                                                                                ?column?                                                                                                                                                
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE POLICY "Usuarios podem atualizar proprio perfil" ON public.profiles FOR UPDATE TO authenticated USING ((auth.uid() = id)) WITH CHECK ((auth.uid() = id));
 CREATE POLICY "Master pode tudo em admin_configs" ON public.admin_configs FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin pode ver propria config" ON public.admin_configs FOR SELECT TO authenticated USING ((admin_id = auth.uid()));
 CREATE POLICY "Admin pode atualizar propria config" ON public.admin_configs FOR UPDATE TO authenticated USING ((admin_id = auth.uid())) WITH CHECK ((admin_id = auth.uid()));
 CREATE POLICY "Master pode tudo em imoveis" ON public.imoveis FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin gerencia proprios imoveis" ON public.imoveis FOR ALL TO authenticated USING (((admin_id = auth.uid()) AND is_active_admin(auth.uid()))) WITH CHECK (((admin_id = auth.uid()) AND is_active_admin(auth.uid())));
 CREATE POLICY "Proprietario pode ver proprios imoveis" ON public.imoveis FOR SELECT TO authenticated USING (((proprietario_id = auth.uid()) OR (proprietario_id_2 = auth.uid())));
 CREATE POLICY "Master pode tudo em reservas" ON public.reservas FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin gerencia reservas dos proprios imoveis" ON public.reservas FOR ALL TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                   +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = reservas.imovel_id) AND (i.admin_id = auth.uid())))))) WITH CHECK ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                                               +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = reservas.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Master pode tudo em despesas_extras" ON public.despesas_extras FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin gerencia despesas dos proprios imoveis" ON public.despesas_extras FOR ALL TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                            +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = despesas_extras.imovel_id) AND (i.admin_id = auth.uid())))))) WITH CHECK ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                                        +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = despesas_extras.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Proprietario pode ver despesas dos proprios imoveis" ON public.despesas_extras FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1                                                                                                                                                   +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = despesas_extras.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid()))))));
 CREATE POLICY "Proprietario gerencia proprios custos fixos" ON public.custos_fixos_proprietario FOR ALL TO authenticated USING ((proprietario_id = auth.uid())) WITH CHECK ((proprietario_id = auth.uid()));
 CREATE POLICY "Master e admin podem inserir perfis" ON public.profiles FOR INSERT TO authenticated USING (true) WITH CHECK ((has_role(auth.uid(), 'master'::app_role) OR has_role(auth.uid(), 'admin'::app_role)));
 CREATE POLICY "Usuarios podem ver proprio perfil" ON public.profiles FOR SELECT TO authenticated USING (((auth.uid() = id) OR has_role(auth.uid(), 'master'::app_role) OR has_role(auth.uid(), 'admin'::app_role)));
 CREATE POLICY "Master e admin e proprio usuario podem ver roles" ON public.user_roles FOR SELECT TO authenticated USING ((has_role(auth.uid(), 'master'::app_role) OR has_role(auth.uid(), 'admin'::app_role) OR (user_id = auth.uid())));
 CREATE POLICY "Admin pode deletar roles nao-master" ON public.user_roles FOR DELETE TO authenticated USING ((has_role(auth.uid(), 'admin'::app_role) AND (role <> 'master'::app_role)));
 CREATE POLICY "Admin gerencia proprios proprietarios" ON public.admin_proprietarios FOR ALL TO authenticated USING ((admin_id = auth.uid())) WITH CHECK ((admin_id = auth.uid()));
 CREATE POLICY "Master pode tudo em admin_proprietarios" ON public.admin_proprietarios FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Proprietario pode ver proprio vinculo" ON public.admin_proprietarios FOR SELECT TO authenticated USING ((proprietario_id = auth.uid()));
 CREATE POLICY "Master pode inserir qualquer role" ON public.user_roles FOR INSERT TO authenticated USING (true) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin pode ver custos fixos dos proprios imoveis" ON public.custos_fixos_proprietario FOR SELECT TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                           +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = custos_fixos_proprietario.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Master pode tudo em custos_fixos_proprietario" ON public.custos_fixos_proprietario FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Proprietario pode inserir despesas dos proprios imoveis" ON public.despesas_extras FOR INSERT TO authenticated USING (true) WITH CHECK ((EXISTS ( SELECT 1                                                                                                                             +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = despesas_extras.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid()))))));
 CREATE POLICY "Proprietario pode deletar despesas dos proprios imoveis" ON public.despesas_extras FOR DELETE TO authenticated USING ((EXISTS ( SELECT 1                                                                                                                                               +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = despesas_extras.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid()))))));
 CREATE POLICY "Master e admin podem atualizar perfis" ON public.profiles FOR UPDATE TO authenticated USING ((has_role(auth.uid(), 'master'::app_role) OR has_role(auth.uid(), 'admin'::app_role))) WITH CHECK ((has_role(auth.uid(), 'master'::app_role) OR has_role(auth.uid(), 'admin'::app_role)));
 CREATE POLICY "Master pode deletar qualquer role" ON public.user_roles FOR DELETE TO authenticated USING (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin pode inserir roles nao-master" ON public.user_roles FOR INSERT TO authenticated USING (true) WITH CHECK ((has_role(auth.uid(), 'admin'::app_role) AND (role <> 'master'::app_role)));
 CREATE POLICY "Admin gerencia custos fixos dos proprios imoveis" ON public.custos_fixos_proprietario FOR ALL TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                              +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = custos_fixos_proprietario.imovel_id) AND (i.admin_id = auth.uid())))))) WITH CHECK ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                              +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = custos_fixos_proprietario.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Master pode tudo em ganhos_extras" ON public.ganhos_extras FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Master pode tudo em limpezas" ON public.limpezas FOR ALL TO authenticated USING (has_role(auth.uid(), 'master'::app_role)) WITH CHECK (has_role(auth.uid(), 'master'::app_role));
 CREATE POLICY "Admin gerencia ganhos extras dos proprios imoveis" ON public.ganhos_extras FOR ALL TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                         +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = ganhos_extras.imovel_id) AND (i.admin_id = auth.uid())))))) WITH CHECK ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                                          +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = ganhos_extras.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Admins can view iCal sync alerts" ON public.ical_sync_alerts FOR SELECT TO public USING ((EXISTS ( SELECT 1                                                                                                                                                                            +
    FROM user_roles                                                                                                                                                                                                                                                                                    +
   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'master'::app_role]))))));
 CREATE POLICY "Admins can update iCal sync alerts" ON public.ical_sync_alerts FOR UPDATE TO public USING ((EXISTS ( SELECT 1                                                                                                                                                                          +
    FROM user_roles                                                                                                                                                                                                                                                                                    +
   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'master'::app_role]))))));
 CREATE POLICY "Admins can delete iCal sync alerts" ON public.ical_sync_alerts FOR DELETE TO public USING ((EXISTS ( SELECT 1                                                                                                                                                                          +
    FROM user_roles                                                                                                                                                                                                                                                                                    +
   WHERE ((user_roles.user_id = auth.uid()) AND (user_roles.role = ANY (ARRAY['admin'::app_role, 'master'::app_role]))))));
 CREATE POLICY "Admin gerencia limpezas dos proprios imoveis" ON public.limpezas FOR ALL TO authenticated USING ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                   +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = limpezas.imovel_id) AND (i.admin_id = auth.uid())))))) WITH CHECK ((is_active_admin(auth.uid()) AND (EXISTS ( SELECT 1                                                                                                                                                               +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = limpezas.imovel_id) AND (i.admin_id = auth.uid()))))));
 CREATE POLICY "Proprietario pode ver reservas dos proprios imoveis" ON public.reservas FOR SELECT TO authenticated USING (((validada_financeiramente = true) AND (EXISTS ( SELECT 1                                                                                                                   +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = reservas.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid())))))));
 CREATE POLICY "Proprietario pode ver limpezas dos proprios imoveis" ON public.limpezas FOR SELECT TO authenticated USING (((EXISTS ( SELECT 1                                                                                                                                                         +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = limpezas.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid()))))) AND ((reserva_id IS NULL) OR (EXISTS ( SELECT 1                                                                                                                                  +
    FROM reservas r                                                                                                                                                                                                                                                                                    +
   WHERE ((r.id = limpezas.reserva_id) AND (r.validada_financeiramente = true)))))));
 CREATE POLICY "Proprietario pode ver ganhos extras dos proprios imoveis" ON public.ganhos_extras FOR SELECT TO authenticated USING (((EXISTS ( SELECT 1                                                                                                                                               +
    FROM imoveis i                                                                                                                                                                                                                                                                                     +
   WHERE ((i.id = ganhos_extras.imovel_id) AND ((i.proprietario_id = auth.uid()) OR (i.proprietario_id_2 = auth.uid()))))) AND ((reserva_id IS NULL) OR (EXISTS ( SELECT 1                                                                                                                             +
    FROM reservas r                                                                                                                                                                                                                                                                                    +
   WHERE ((r.id = ganhos_extras.reserva_id) AND (r.validada_financeiramente = true)))))));
(39 rows)

